package fileService

import (
	"bytes"
	"context"
	"fmt"
	"io"
	"mime/multipart"
	"net/http"
	"net/url"

	"github.com/HTMLuke/OneLab-API/config"
	"github.com/HTMLuke/OneLab-API/secretProvider"
)

// PaperlessService handles sending files to Paperless-ngx.
type PaperlessService struct {
	checkURL      string
	addUrl        string
	token         string
	cnfService    config.ConfigService
	secretService secretProvider.SecretService
}

func NewPaperlessService(cfgService config.ConfigService, secretService secretProvider.SecretService) *PaperlessService {
	baseURL := cfgService.GetPaperlessBaseUrl()
	token := secretService.GetPaperlessToken()
	checkURL, _ := url.JoinPath(baseURL, "api/documents/")
	addUrl, _ := url.JoinPath(baseURL, "api/documents/post_document/")
	return &PaperlessService{
		checkURL:      checkURL,
		addUrl:        addUrl,
		token:         token,
		cnfService:    cfgService,
		secretService: secretService,
	}
}

func (s *PaperlessService) AddFile(ctx context.Context, file []byte, filename string) error {
	// Initialize buffer and multipart writer
	body := &bytes.Buffer{}
	writer := multipart.NewWriter(body)

	// Create the form file field (Paperless strictly requires the field name to be "document")
	part, err := writer.CreateFormFile("document", filename)
	if err != nil {
		return fmt.Errorf("failed to create multipart form file: %v", err)
	}

	// Stream the []byte into the multipart field
	_, err = io.Copy(part, bytes.NewReader(file))
	if err != nil {
		return fmt.Errorf("failed to copy file bytes to multipart: %v", err)
	}

	// CRITICAL: Close the writer BEFORE creating the request.
	// This appends the final multipart boundary to the buffer.
	if err := writer.Close(); err != nil {
		return fmt.Errorf("failed to close multipart writer: %v", err)
	}

	// Prepare the HTTP request
	req, err := http.NewRequestWithContext(ctx, "POST", s.addUrl, body)
	if err != nil {
		return fmt.Errorf("failed to create request: %v", err)
	}

	// The Content-Type header MUST include the specific boundary generated by the writer!
	req.Header.Set("Content-Type", writer.FormDataContentType())

	// Set the Authorization Header for Paperless
	if s.token != "" {
		req.Header.Set("Authorization", fmt.Sprintf("Token %s", s.token))
	}

	// 5. Execute the request
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return fmt.Errorf("failed to send request to paperless: %v", err)
	}
	defer resp.Body.Close()

	// 6. Validate the response
	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		bodyBytes, _ := io.ReadAll(resp.Body)
		return fmt.Errorf("paperless upload failed: status %d, response: %s", resp.StatusCode, string(bodyBytes))
	}

	return nil
}
func (s *PaperlessService) GetFile(ctx context.Context, fileID string) ([]byte, error) {
	return nil, fmt.Errorf("GetFile not implemented yet for Paperless")
}
func (s *PaperlessService) LookupFile(ctx context.Context, filename string) (any, error) {
	// TODO: Implement Paperless-ngx file lookup logic here.
	return nil, fmt.Errorf("LookupFile not implemented yet for Paperless")
}

func (s *PaperlessService) CheckStatus(ctx context.Context) error {
	req, err := http.NewRequestWithContext(ctx, "GET", s.checkURL, nil)
	if err != nil {
		return err
	}
	req.Header.Set("Authorization", fmt.Sprintf("Token %s", s.token))

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()

	if resp.StatusCode == http.StatusUnauthorized || resp.StatusCode == http.StatusForbidden {
		return fmt.Errorf("paperless authentication failed with status: %d", resp.StatusCode)
	}

	return nil
}
