package fileService

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"log/slog"
	"mime"
	"mime/multipart"
	"net/http"
	"net/url"
	"os"
	"strings"

	"github.com/HTMLuke/OneLab-API/secretProvider"
)

// PaperlessService handles sending files to Paperless-ngx.
type PaperlessService struct {
	checkURL     string
	addUrl       string
	getUrl       string
	apiLookupUrl string
	token        string
	logger       *slog.Logger
}

type PaperlessFileMetadata struct {
	ID                  int     `json:"id"`
	Correspondent       int     `json:"correspondent"`
	DocumentType        int     `json:"document_type"`
	StoragePath         *string `json:"storage_path"`
	Title               string  `json:"title"`
	Content             string  `json:"content"`
	Tags                []int   `json:"tags"`
	Created             string  `json:"created"`
	CreatedDate         string  `json:"created_date"`
	Modified            string  `json:"modified"`
	Added               string  `json:"added"`
	DeletedAt           *string `json:"deleted_at"`
	ArchiveSerialNumber *string `json:"archive_serial_number"`
	OriginalFileName    string  `json:"original_file_name"`
	ArchivedFileName    string  `json:"archived_file_name"`
	Owner               int     `json:"owner"`
	UserCanChange       bool    `json:"user_can_change"`
	IsSharedByRequester bool    `json:"is_shared_by_requester"`
	Notes               []any   `json:"notes"`
	CustomFields        []any   `json:"custom_fields"`
	PageCount           int     `json:"page_count"`
	MimeType            string  `json:"mime_type"`
}

type PaperlessFileResponse struct {
	ID               int    `json:"id"`
	Title            string `json:"title"`
	OriginalFileName string `json:"original_file_name"`
	MimeType         string `json:"mime_type"`
	Created          string `json:"created"`
	PageCount        int    `json:"page_count"`
}

type PaperlessSearchResponse struct {
	Count    int                     `json:"count"`
	Next     *string                 `json:"next"`
	Previous *string                 `json:"previous"`
	All      []int                   `json:"all"`
	Results  []PaperlessFileMetadata `json:"results"`
}

func init() {
	RegisterIntegration("paperless", func(baseURL string, s secretProvider.SecretService, logger *slog.Logger) (IntegrationService, error) {
		return NewPaperlessService(baseURL, s, logger)
	})
}

func NewPaperlessService(baseURL string, secretService secretProvider.SecretService, logger *slog.Logger) (*PaperlessService, error) {
	if strings.TrimSpace(baseURL) == "" {
		baseURL = strings.TrimSpace(os.Getenv("ONELAB_PAPERLESS_BASE_URL"))
	}
	if baseURL == "" {
		return nil, fmt.Errorf("required environment variable %q is not set", "ONELAB_PAPERLESS_BASE_URL")
	}
	token, err := secretService.GetSecret("ONELAB_PAPERLESS_TOKEN")
	if err != nil {
		return nil, err
	}
	checkURL, _ := url.JoinPath(baseURL, "api/documents/")
	addUrl, _ := url.JoinPath(baseURL, "api/documents/post_document/")
	getUrl, _ := url.JoinPath(baseURL, "api/documents/")
	apiLookupUrl, _ := url.JoinPath(baseURL, "api/documents/")
	return &PaperlessService{
		checkURL:     checkURL,
		addUrl:       addUrl,
		getUrl:       getUrl,
		token:        token,
		apiLookupUrl: apiLookupUrl,
		logger:       logger,
	}, nil
}

func (s *PaperlessService) AddFile(ctx context.Context, file []byte, filename string) error {
	s.log(ctx, slog.LevelDebug, "paperless upload started", "bytes", len(file))
	// Initialize buffer and multipart writer
	body := &bytes.Buffer{}
	writer := multipart.NewWriter(body)

	// Create the form file field (Paperless strictly requires the field name to be "document")
	part, err := writer.CreateFormFile("document", filename)
	if err != nil {
		return fmt.Errorf("failed to create multipart form file: %v", err)
	}

	// Stream the []byte into the multipart field
	_, err = io.Copy(part, bytes.NewReader(file))
	if err != nil {
		return fmt.Errorf("failed to copy file bytes to multipart: %v", err)
	}

	// CRITICAL: Close the writer BEFORE creating the request.
	// This appends the final multipart boundary to the buffer.
	if err := writer.Close(); err != nil {
		return fmt.Errorf("failed to close multipart writer: %v", err)
	}

	// Prepare the HTTP request
	req, err := http.NewRequestWithContext(ctx, "POST", s.addUrl, body)
	if err != nil {
		return fmt.Errorf("failed to create request: %v", err)
	}

	// The Content-Type header MUST include the specific boundary generated by the writer!
	req.Header.Set("Content-Type", writer.FormDataContentType())

	// Set the Authorization Header for Paperless
	if s.token != "" {
		req.Header.Set("Authorization", fmt.Sprintf("Token %s", s.token))
	}

	// 5. Execute the request
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return fmt.Errorf("failed to send request to paperless: %v", err)
	}
	defer resp.Body.Close()

	// 6. Validate the response
	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		s.log(ctx, slog.LevelWarn, "paperless upload failed", "status", resp.StatusCode)
		bodyBytes, _ := io.ReadAll(resp.Body)
		return fmt.Errorf("paperless upload failed: status %d, response: %s", resp.StatusCode, string(bodyBytes))
	}

	s.log(ctx, slog.LevelInfo, "paperless upload completed", "status", resp.StatusCode)
	return nil
}
func (s *PaperlessService) GetFile(ctx context.Context, fileID string) ([]byte, error) {
	fileData, _, err := s.GetFileWithName(ctx, fileID)
	return fileData, err
}

func (s *PaperlessService) GetFileWithName(ctx context.Context, fileID string) ([]byte, string, error) {
	s.log(ctx, slog.LevelDebug, "paperless download started")
	// Build the download URL: .../api/documents/{id}/download/
	downloadPath, err := url.JoinPath(s.apiLookupUrl, fileID, "download/")
	if err != nil {
		return nil, "", fmt.Errorf("failed to build download URL: %v", err)
	}
	//create request with context
	req, err := http.NewRequestWithContext(ctx, "GET", downloadPath, nil)
	if err != nil {
		return nil, "", err
	}

	// Set required headers
	if s.token != "" {
		req.Header.Set("Authorization", fmt.Sprintf("Token %s", s.token))
	}

	//  Send the request
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, "", fmt.Errorf("failed to send download request to paperless: %v", err)
	}
	defer resp.Body.Close()

	// Handle non-success HTTP statuses
	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		s.log(ctx, slog.LevelWarn, "paperless download failed", "status", resp.StatusCode)
		bodyBytes, _ := io.ReadAll(resp.Body)
		return nil, "", fmt.Errorf("paperless download failed: status %d, response: %s", resp.StatusCode, string(bodyBytes))
	}

	filename, err := filenameFromContentDisposition(resp.Header.Get("Content-Disposition"))
	if err != nil {
		return nil, "", err
	}

	// Read the raw file binary data into a byte slice
	fileData, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, "", fmt.Errorf("failed to read paperless file content: %v", err)
	}

	s.log(ctx, slog.LevelInfo, "paperless download completed", "bytes", len(fileData), "status", resp.StatusCode)
	return fileData, filename, nil
}

func filenameFromContentDisposition(value string) (string, error) {
	if value == "" {
		return "", fmt.Errorf("paperless download response does not contain a Content-Disposition header")
	}
	_, params, err := mime.ParseMediaType(value)
	if err != nil {
		return "", fmt.Errorf("failed to parse paperless Content-Disposition header: %w", err)
	}
	filename, ok := params["filename"]
	if !ok || filename == "" {
		return "", fmt.Errorf("paperless Content-Disposition header does not contain a filename")
	}
	return filename, nil
}
func (s *PaperlessService) LookupFile(ctx context.Context, filename string) (any, error) {
	s.log(ctx, slog.LevelDebug, "paperless lookup started")
	req, err := http.NewRequestWithContext(ctx, "GET", s.apiLookupUrl, nil)
	if err != nil {
		return nil, err
	}

	q := req.URL.Query()
	q.Add("title__icontains", filename)
	req.URL.RawQuery = q.Encode()
	req.Header.Set("Authorization", fmt.Sprintf("Token %s", s.token))
	req.Header.Set("Accept", "application/json")
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		bodyBytes, _ := io.ReadAll(resp.Body)
		return nil, fmt.Errorf("request failed: received status code %d, response: %s", resp.StatusCode, string(bodyBytes))
	}
	var searchResp PaperlessSearchResponse
	if err := json.NewDecoder(resp.Body).Decode(&searchResp); err != nil {
		return nil, fmt.Errorf("failed to decode paperless lookup response: %v", err)
	}
	var results []PaperlessFileResponse
	for _, entry := range searchResp.Results {
		results = append(results, PaperlessFileResponse{
			ID:               entry.ID,
			Title:            entry.Title,
			OriginalFileName: entry.OriginalFileName,
			MimeType:         entry.MimeType,
			Created:          entry.Created,
			PageCount:        entry.PageCount,
		})
	}
	s.log(ctx, slog.LevelInfo, "paperless lookup completed", "result_count", len(results), "status", resp.StatusCode)
	return results, nil
}
func (s *PaperlessService) CheckStatus(ctx context.Context) error {
	s.log(ctx, slog.LevelDebug, "paperless health check started")
	req, err := http.NewRequestWithContext(ctx, "GET", s.checkURL, nil)
	if err != nil {
		return err
	}
	req.Header.Set("Authorization", fmt.Sprintf("Token %s", s.token))

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()

	if resp.StatusCode == http.StatusUnauthorized || resp.StatusCode == http.StatusForbidden {
		s.log(ctx, slog.LevelWarn, "paperless health check failed", "status", resp.StatusCode)
		return fmt.Errorf("paperless authentication failed with status: %d", resp.StatusCode)
	}

	s.log(ctx, slog.LevelDebug, "paperless health check completed", "status", resp.StatusCode)
	return nil
}

func (s *PaperlessService) log(ctx context.Context, level slog.Level, message string, args ...any) {
	if s.logger != nil {
		s.logger.Log(ctx, level, message, args...)
	}
}
